const express = require('express')
const db = require('../models')
const app = express.Router()
const BLOG = require('../app/Controllers/BlogController')


app.route('/all')
    .get(BLOG.list_all)
app.route('/all/Category/:category')
    .get(BLOG.list_Category)
app.route('/all/Title/:title')
    .get(BLOG.list_Title)
app.route('/:id')
    .get(BLOG.blog_detail)
app.route('/User/:user')
    .get(BLOG.blog_User)
app.route('/New')
    .post(BLOG.New_blog)
app.route('/Update/:id')
    .put(BLOG.Update_blog)
app.route('/Delete/:id')
    .delete(BLOG.Delete_blog)

app.route('/Favorite')
    .post(BLOG.Add_favorite)
app.route('/get/Favorite/:id')
    .get(BLOG.get_favorite)
app.route('/Delete/Favorite/:id')
    .delete(BLOG.Delete_favorite)

app.route('/readLater')
    .post(BLOG.Add_bookmark)
app.route('/get/readLater/:id')
    .get(BLOG.get_bookmark)
app.route('/Delete/readLater/:id')
    .delete(BLOG.Delete_bookmark)

module.exports = app;